language: python
python:
  - "2.6"
  - "2.7"

# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Install tox travis to be able to use tox environment conditionally under travis CI
install: pip install tox-travis

script: tox

notifications:
  email:
    recipients:
      - massimiliano.culpo@gmail.com
    on_success: change
    on_failure: always
