[tox]
envlist=py26, py27, pylint, flake8

[tox:travis]
2.6 = py26
2.7 = py27

[testenv]
deps=coveralls
passenv=HOME TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH
env=
    EMAIL="spack@example.com"
    GIT_AUTHOR_NAME="Test User"
whitelist_externals=git
commands=
    coverage run --source=lib --omit=lib/spack/spack/test/*,lib/spack/env/*,lib/spack/docs/* bin/spack test
    - python {toxinidir}/run_coveralls.py

[testenv:pylint]
commands =
    - pylint --rcfile {toxinidir}/pylint.ini {toxinidir}/lib/spack/spack
deps =
    pylint

[testenv:flake8]
commands =
    - flake8 --format pylint --config {toxinidir}/flake8.ini {toxinidir}/lib
deps =
    flake8
