[tox]
envlist=py26, py27

[tox:travis]
2.6 = py26
2.7 = py27

[testenv]
deps=coveralls
passenv=HOME
whitelist_externals=git
commands=
    git config --global user.email "spack@example.com"
    git config --global user.name "Test User"
    coverage run --source=lib --omit=lib/spack/spack/test/*,lib/spack/env/*,lib/spack/docs/* bin/spack test

[flake8]
ignore = W391,F841
max-line-length = 120