[tox]
envlist=py26, py27, pylint, flake8

[tox:travis]
2.6 = py26
2.7 = py27

[testenv]
deps=coveralls
passenv=HOME
whitelist_externals=git
commands=
    git config --global user.email "spack@example.com"
    git config --global user.name "Test User"
    coverage run --source=lib --omit=lib/spack/spack/test/*,lib/spack/env/*,lib/spack/docs/* bin/spack test

[testenv:pylint]
commands =
    - pylint --rcfile {toxinidir}/pylint.ini {toxinidir}/lib/spack/spack
deps =
    pylint

[testenv:flake8]
commands =
    - flake8 --format pylint --config {toxinidir}/flake8.ini {toxinidir}/lib
deps =
    flake8
